services:
  db:
    image: postgres:16
    container_name: person_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: person_app
    environment:
      DB_DSN: postgres://postgres:postgres@db:5432/person_db?sslmode=disable
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8080:8080" 
volumes:
  pgdata:

networks:
  backend: